// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "qbills/models/domain"

	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"

	web "qbills/models/web"
)

// AdminService is an autogenerated mock type for the AdminService type
type AdminService struct {
	mock.Mock
}

// CreateAdmin provides a mock function with given fields: ctx, request
func (_m *AdminService) CreateAdmin(ctx echo.Context, request web.AdminCreateRequest) (*domain.Admin, error) {
	ret := _m.Called(ctx, request)

	var r0 *domain.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, web.AdminCreateRequest) (*domain.Admin, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, web.AdminCreateRequest) *domain.Admin); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, web.AdminCreateRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAdmin provides a mock function with given fields: ctx, id
func (_m *AdminService) DeleteAdmin(ctx echo.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx
func (_m *AdminService) FindAll(ctx echo.Context) ([]domain.Admin, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context) ([]domain.Admin, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(echo.Context) []domain.Admin); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: ctx, id
func (_m *AdminService) FindById(ctx echo.Context, id int) (*domain.Admin, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, int) (*domain.Admin, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, int) *domain.Admin); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUsername provides a mock function with given fields: ctx, name
func (_m *AdminService) FindByUsername(ctx echo.Context, name string) (*domain.Admin, error) {
	ret := _m.Called(ctx, name)

	var r0 *domain.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, string) (*domain.Admin, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, string) *domain.Admin); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoginAdmin provides a mock function with given fields: ctx, request
func (_m *AdminService) LoginAdmin(ctx echo.Context, request web.AdminLoginRequest) (*domain.Admin, error) {
	ret := _m.Called(ctx, request)

	var r0 *domain.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, web.AdminLoginRequest) (*domain.Admin, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, web.AdminLoginRequest) *domain.Admin); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, web.AdminLoginRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAdmin provides a mock function with given fields: ctx, request, id
func (_m *AdminService) UpdateAdmin(ctx echo.Context, request web.AdminUpdateRequest, id int) (*domain.Admin, error) {
	ret := _m.Called(ctx, request, id)

	var r0 *domain.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, web.AdminUpdateRequest, int) (*domain.Admin, error)); ok {
		return rf(ctx, request, id)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, web.AdminUpdateRequest, int) *domain.Admin); ok {
		r0 = rf(ctx, request, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, web.AdminUpdateRequest, int) error); ok {
		r1 = rf(ctx, request, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAdminService creates a new instance of AdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminService {
	mock := &AdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
