// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "qbills/models/domain"

	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"

	web "qbills/models/web"
)

// CashierService is an autogenerated mock type for the CashierService type
type CashierService struct {
	mock.Mock
}

// CreateCashier provides a mock function with given fields: ctx, request
func (_m *CashierService) CreateCashier(ctx echo.Context, request web.CashierCreateRequest) (*domain.Cashier, error) {
	ret := _m.Called(ctx, request)

	var r0 *domain.Cashier
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, web.CashierCreateRequest) (*domain.Cashier, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, web.CashierCreateRequest) *domain.Cashier); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Cashier)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, web.CashierCreateRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCashier provides a mock function with given fields: ctx, id
func (_m *CashierService) DeleteCashier(ctx echo.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx
func (_m *CashierService) FindAll(ctx echo.Context) ([]domain.Cashier, int, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Cashier
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(echo.Context) ([]domain.Cashier, int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(echo.Context) []domain.Cashier); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Cashier)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context) int); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(echo.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindById provides a mock function with given fields: ctx, id
func (_m *CashierService) FindById(ctx echo.Context, id int) (*domain.Cashier, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Cashier
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, int) (*domain.Cashier, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, int) *domain.Cashier); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Cashier)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUsername provides a mock function with given fields: ctx, name
func (_m *CashierService) FindByUsername(ctx echo.Context, name string) (*domain.Cashier, error) {
	ret := _m.Called(ctx, name)

	var r0 *domain.Cashier
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, string) (*domain.Cashier, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, string) *domain.Cashier); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Cashier)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoginCashier provides a mock function with given fields: ctx, request
func (_m *CashierService) LoginCashier(ctx echo.Context, request web.CashierLoginRequest) (*domain.Cashier, error) {
	ret := _m.Called(ctx, request)

	var r0 *domain.Cashier
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, web.CashierLoginRequest) (*domain.Cashier, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, web.CashierLoginRequest) *domain.Cashier); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Cashier)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, web.CashierLoginRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCashier provides a mock function with given fields: ctx, request, id
func (_m *CashierService) UpdateCashier(ctx echo.Context, request web.CashierUpdateRequest, id int) (*domain.Cashier, error) {
	ret := _m.Called(ctx, request, id)

	var r0 *domain.Cashier
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, web.CashierUpdateRequest, int) (*domain.Cashier, error)); ok {
		return rf(ctx, request, id)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, web.CashierUpdateRequest, int) *domain.Cashier); ok {
		r0 = rf(ctx, request, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Cashier)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, web.CashierUpdateRequest, int) error); ok {
		r1 = rf(ctx, request, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCashierService creates a new instance of CashierService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCashierService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CashierService {
	mock := &CashierService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
