// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "qbills/models/domain"

	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"

	web "qbills/models/web"
)

// ConvertPointService is an autogenerated mock type for the ConvertPointService type
type ConvertPointService struct {
	mock.Mock
}

// CreateConvertPoint provides a mock function with given fields: ctx, request
func (_m *ConvertPointService) CreateConvertPoint(ctx echo.Context, request web.ConvertPointRequest) (*domain.ConvertPoint, error) {
	ret := _m.Called(ctx, request)

	var r0 *domain.ConvertPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, web.ConvertPointRequest) (*domain.ConvertPoint, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, web.ConvertPointRequest) *domain.ConvertPoint); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ConvertPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, web.ConvertPointRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteConvertPoint provides a mock function with given fields: ctx, id
func (_m *ConvertPointService) DeleteConvertPoint(ctx echo.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields:
func (_m *ConvertPointService) FindAll() ([]domain.ConvertPoint, error) {
	ret := _m.Called()

	var r0 []domain.ConvertPoint
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.ConvertPoint, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.ConvertPoint); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ConvertPoint)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: ctx, id
func (_m *ConvertPointService) FindById(ctx echo.Context, id int) (*domain.ConvertPoint, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.ConvertPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, int) (*domain.ConvertPoint, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, int) *domain.ConvertPoint); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ConvertPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateConvertPoint provides a mock function with given fields: ctx, request, id
func (_m *ConvertPointService) UpdateConvertPoint(ctx echo.Context, request web.ConvertPointRequest, id int) (*domain.ConvertPoint, error) {
	ret := _m.Called(ctx, request, id)

	var r0 *domain.ConvertPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, web.ConvertPointRequest, int) (*domain.ConvertPoint, error)); ok {
		return rf(ctx, request, id)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, web.ConvertPointRequest, int) *domain.ConvertPoint); ok {
		r0 = rf(ctx, request, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ConvertPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, web.ConvertPointRequest, int) error); ok {
		r1 = rf(ctx, request, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewConvertPointService creates a new instance of ConvertPointService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConvertPointService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConvertPointService {
	mock := &ConvertPointService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
