// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// ConvertPointHandler is an autogenerated mock type for the ConvertPointHandler type
type ConvertPointHandler struct {
	mock.Mock
}

// CreateConvertPointHandler provides a mock function with given fields: ctx
func (_m *ConvertPointHandler) CreateConvertPointHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteConvertPointHandler provides a mock function with given fields: ctx
func (_m *ConvertPointHandler) DeleteConvertPointHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllConvertPointHandler provides a mock function with given fields: ctx
func (_m *ConvertPointHandler) GetAllConvertPointHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetConvertPointHandler provides a mock function with given fields: ctx
func (_m *ConvertPointHandler) GetConvertPointHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateConvertPointHandler provides a mock function with given fields: ctx
func (_m *ConvertPointHandler) UpdateConvertPointHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConvertPointHandler creates a new instance of ConvertPointHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConvertPointHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConvertPointHandler {
	mock := &ConvertPointHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
