// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// MembershipCardHandler is an autogenerated mock type for the MembershipCardHandler type
type MembershipCardHandler struct {
	mock.Mock
}

// PrintMembershipCardHandler provides a mock function with given fields: ctx
func (_m *MembershipCardHandler) PrintMembershipCardHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMembershipCardHandler creates a new instance of MembershipCardHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMembershipCardHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MembershipCardHandler {
	mock := &MembershipCardHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
