// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// MembershipPointHandler is an autogenerated mock type for the MembershipPointHandler type
type MembershipPointHandler struct {
	mock.Mock
}

// FindAllMembershipPointHandler provides a mock function with given fields: ctx
func (_m *MembershipPointHandler) FindAllMembershipPointHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByIdMembershipPointHandler provides a mock function with given fields: ctx
func (_m *MembershipPointHandler) FindByIdMembershipPointHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindDecreaseMembershipPointHandler provides a mock function with given fields: ctx
func (_m *MembershipPointHandler) FindDecreaseMembershipPointHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindIncreaseMembershipPointHandler provides a mock function with given fields: ctx
func (_m *MembershipPointHandler) FindIncreaseMembershipPointHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMembershipPointHandler provides a mock function with given fields: ctx
func (_m *MembershipPointHandler) UpdateMembershipPointHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMembershipPointHandler creates a new instance of MembershipPointHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMembershipPointHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MembershipPointHandler {
	mock := &MembershipPointHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
