// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "qbills/models/domain"

	mock "github.com/stretchr/testify/mock"

	web "qbills/models/web"
)

// MembershipPointService is an autogenerated mock type for the MembershipPointService type
type MembershipPointService struct {
	mock.Mock
}

// FindAllMembershipPointByIdService provides a mock function with given fields: membershipId
func (_m *MembershipPointService) FindAllMembershipPointByIdService(membershipId uint) ([]domain.MembershipPoint, error) {
	ret := _m.Called(membershipId)

	var r0 []domain.MembershipPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.MembershipPoint, error)); ok {
		return rf(membershipId)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.MembershipPoint); ok {
		r0 = rf(membershipId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MembershipPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(membershipId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIdMembershipPointService provides a mock function with given fields: id
func (_m *MembershipPointService) FindByIdMembershipPointService(id uint) (*domain.MembershipPoint, error) {
	ret := _m.Called(id)

	var r0 *domain.MembershipPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.MembershipPoint, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.MembershipPoint); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MembershipPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindDecreaseMembershipPointService provides a mock function with given fields:
func (_m *MembershipPointService) FindDecreaseMembershipPointService() ([]domain.MembershipPoint, error) {
	ret := _m.Called()

	var r0 []domain.MembershipPoint
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.MembershipPoint, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.MembershipPoint); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MembershipPoint)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindIncreaseMembershipPointService provides a mock function with given fields:
func (_m *MembershipPointService) FindIncreaseMembershipPointService() ([]domain.MembershipPoint, error) {
	ret := _m.Called()

	var r0 []domain.MembershipPoint
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.MembershipPoint, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.MembershipPoint); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MembershipPoint)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMembershipPointService provides a mock function with given fields: request
func (_m *MembershipPointService) UpdateMembershipPointService(request web.MembershipPointCreate) (*domain.MembershipPoint, error) {
	ret := _m.Called(request)

	var r0 *domain.MembershipPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(web.MembershipPointCreate) (*domain.MembershipPoint, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(web.MembershipPointCreate) *domain.MembershipPoint); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MembershipPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(web.MembershipPointCreate) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMembershipPointService creates a new instance of MembershipPointService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMembershipPointService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MembershipPointService {
	mock := &MembershipPointService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
