// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// PaymentMethodHandler is an autogenerated mock type for the PaymentMethodHandler type
type PaymentMethodHandler struct {
	mock.Mock
}

// CreatePaymentMethodHandler provides a mock function with given fields: ctx
func (_m *PaymentMethodHandler) CreatePaymentMethodHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePaymentMethodHandler provides a mock function with given fields: ctx
func (_m *PaymentMethodHandler) DeletePaymentMethodHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPaymentMethodByNameHandler provides a mock function with given fields: ctx
func (_m *PaymentMethodHandler) GetPaymentMethodByNameHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPaymentMethodHandler provides a mock function with given fields: ctx
func (_m *PaymentMethodHandler) GetPaymentMethodHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPaymentMethodsHandler provides a mock function with given fields: ctx
func (_m *PaymentMethodHandler) GetPaymentMethodsHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePaymentMethodHandler provides a mock function with given fields: ctx
func (_m *PaymentMethodHandler) UpdatePaymentMethodHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPaymentMethodHandler creates a new instance of PaymentMethodHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentMethodHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentMethodHandler {
	mock := &PaymentMethodHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
