// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "qbills/models/domain"

	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"

	web "qbills/models/web"
)

// StockService is an autogenerated mock type for the StockService type
type StockService struct {
	mock.Mock
}

// FindAllStockService provides a mock function with given fields: ctx
func (_m *StockService) FindAllStockService(ctx echo.Context) ([]domain.Stock, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Stock
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context) ([]domain.Stock, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(echo.Context) []domain.Stock); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Stock)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIdStockService provides a mock function with given fields: ctx, id
func (_m *StockService) FindByIdStockService(ctx echo.Context, id uint) (*domain.Stock, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Stock
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, uint) (*domain.Stock, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, uint) *domain.Stock); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Stock)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindDecreaseStockService provides a mock function with given fields: ctx
func (_m *StockService) FindDecreaseStockService(ctx echo.Context) ([]domain.Stock, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Stock
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context) ([]domain.Stock, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(echo.Context) []domain.Stock); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Stock)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindIncreaseStockService provides a mock function with given fields: ctx
func (_m *StockService) FindIncreaseStockService(ctx echo.Context) ([]domain.Stock, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Stock
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context) ([]domain.Stock, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(echo.Context) []domain.Stock); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Stock)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStockService provides a mock function with given fields: ctx, request
func (_m *StockService) UpdateStockService(ctx echo.Context, request web.StockCreateRequest) (*domain.Stock, error) {
	ret := _m.Called(ctx, request)

	var r0 *domain.Stock
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, web.StockCreateRequest) (*domain.Stock, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, web.StockCreateRequest) *domain.Stock); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Stock)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, web.StockCreateRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStockService creates a new instance of StockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StockService {
	mock := &StockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
