// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// SuperAdminHandler is an autogenerated mock type for the SuperAdminHandler type
type SuperAdminHandler struct {
	mock.Mock
}

// GetSuperAdminHandler provides a mock function with given fields: ctx
func (_m *SuperAdminHandler) GetSuperAdminHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSuperAdminsHandler provides a mock function with given fields: ctx
func (_m *SuperAdminHandler) GetSuperAdminsHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoginSuperAdminHandler provides a mock function with given fields: ctx
func (_m *SuperAdminHandler) LoginSuperAdminHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSuperAdminHandler creates a new instance of SuperAdminHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSuperAdminHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *SuperAdminHandler {
	mock := &SuperAdminHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
