// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "qbills/models/domain"

	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"

	web "qbills/models/web"
)

// SuperAdminService is an autogenerated mock type for the SuperAdminService type
type SuperAdminService struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: ctx
func (_m *SuperAdminService) FindAll(ctx echo.Context) ([]domain.SuperAdmin, error) {
	ret := _m.Called(ctx)

	var r0 []domain.SuperAdmin
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context) ([]domain.SuperAdmin, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(echo.Context) []domain.SuperAdmin); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SuperAdmin)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: ctx, id
func (_m *SuperAdminService) FindById(ctx echo.Context, id int) (*domain.SuperAdmin, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.SuperAdmin
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, int) (*domain.SuperAdmin, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, int) *domain.SuperAdmin); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SuperAdmin)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoginSuperAdmin provides a mock function with given fields: ctx, request
func (_m *SuperAdminService) LoginSuperAdmin(ctx echo.Context, request web.SuperAdminLoginRequest) (*domain.SuperAdmin, error) {
	ret := _m.Called(ctx, request)

	var r0 *domain.SuperAdmin
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, web.SuperAdminLoginRequest) (*domain.SuperAdmin, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, web.SuperAdminLoginRequest) *domain.SuperAdmin); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SuperAdmin)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, web.SuperAdminLoginRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSuperAdminService creates a new instance of SuperAdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSuperAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SuperAdminService {
	mock := &SuperAdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
